<?php

$title = 'My artists';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('artist', array('action'=>'add'));?>">Add new artist</a>
</p>

<table class="table">
<tr>
    <th>Label</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $artist) : ?>
<tr>
    <td><?php echo $this->escapeHtml($artist->label);?></td>
    <td>
        <a href="<?php echo $this->url('artist',
            array('action'=>'edit', 'id' => $artist->id));?>">Edit</a>
        <a href="<?php echo $this->url('artist',
            array('action'=>'delete', 'id' => $artist->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php
// add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'artist'
    )
);
?>